export const demoInventory = [
  {
    id: "inv-001",
    productId: "prod-001",
    productName: "Basmati Rice 5kg",
    sku: "RICE-5KG",
    category: "Groceries",
    price: 420,
    stock: 18,
    lowStockThreshold: 10,
    status: "In Stock",
  },
  {
    id: "inv-002",
    productId: "prod-002",
    productName: "Sunflower Oil 1L",
    sku: "OIL-1L",
    category: "Groceries",
    price: 145,
    stock: 7,
    lowStockThreshold: 10,
    status: "Low Stock",
  },
  {
    id: "inv-003",
    productId: "prod-003",
    productName: "Wheat Flour 10kg",
    sku: "FLOUR-10KG",
    category: "Groceries",
    price: 510,
    stock: 24,
    lowStockThreshold: 8,
    status: "In Stock",
  },
  {
    id: "inv-004",
    productId: "prod-004",
    productName: "Toor Dal 1kg",
    sku: "DAL-1KG",
    category: "Groceries",
    price: 165,
    stock: 5,
    lowStockThreshold: 10,
    status: "Low Stock",
  },
  {
    id: "inv-005",
    productId: "prod-005",
    productName: "Tea 500g",
    sku: "TEA-500G",
    category: "Beverages",
    price: 230,
    stock: 42,
    lowStockThreshold: 10,
    status: "In Stock",
  },
];

export const demoProcurementProducts = [
  {
    id: "prod-101",
    productId: "prod-101",
    name: "Basmati Rice 25kg",
    productName: "Basmati Rice 25kg",
    sku: "BAS-25KG",
    category: "Groceries",
    price: 1850,
    supplierName: "FreshMart Suppliers",
    availableStock: 240,
    minimumOrderQuantity: 10,
  },
  {
    id: "prod-102",
    productId: "prod-102",
    name: "Sunflower Oil 15L",
    productName: "Sunflower Oil 15L",
    sku: "OIL-15L",
    category: "Groceries",
    price: 1980,
    supplierName: "National Distributors",
    availableStock: 180,
    minimumOrderQuantity: 5,
  },
  {
    id: "prod-103",
    productId: "prod-103",
    name: "Wheat Flour 25kg",
    productName: "Wheat Flour 25kg",
    sku: "FLOUR-25KG",
    category: "Groceries",
    price: 1120,
    supplierName: "FreshMart Suppliers",
    availableStock: 320,
    minimumOrderQuantity: 10,
  },
  {
    id: "prod-104",
    productId: "prod-104",
    name: "Toor Dal 25kg",
    productName: "Toor Dal 25kg",
    sku: "DAL-25KG",
    category: "Groceries",
    price: 3150,
    supplierName: "Wholesale Hub",
    availableStock: 95,
    minimumOrderQuantity: 5,
  },
];

export const demoProcurementRequests = [
  {
    id: "PR-1001",
    productId: "prod-101",
    productName: "Basmati Rice 25kg",
    quantity: 20,
    totalAmount: 37000,
    commitmentPercentage: 10,
    status: "pending",
    createdAt: "2026-10-01",
  },
  {
    id: "PR-1002",
    productId: "prod-103",
    productName: "Wheat Flour 25kg",
    quantity: 15,
    totalAmount: 16800,
    commitmentPercentage: 10,
    status: "accepted",
    createdAt: "2026-09-29",
  },
];

export const demoResaleListings = [
  {
    id: "listing-001",
    productId: "resale-001",
    productName: "Premium Tea 500g",
    sku: "TEA-500G",
    category: "Beverages",
    description: "Excess stock available for quick resale.",
    price: 185,
    quantity: 35,
    sellerName: "City Corner Store",
    status: "active",
  },
  {
    id: "listing-002",
    productId: "resale-002",
    productName: "Cooking Oil 5L",
    sku: "OIL-5L",
    category: "Groceries",
    description: "Good condition excess inventory.",
    price: 620,
    quantity: 12,
    sellerName: "Green Basket",
    status: "active",
  },
  {
    id: "listing-003",
    productId: "resale-003",
    productName: "Sugar 10kg",
    sku: "SUGAR-10KG",
    category: "Groceries",
    description: "Bulk excess stock.",
    price: 490,
    quantity: 20,
    sellerName: "Metro Mart",
    status: "active",
  },
];

export const demoMyListings = [
  {
    id: "my-listing-001",
    productId: "inv-003",
    productName: "Wheat Flour 10kg",
    sku: "FLOUR-10KG",
    category: "Groceries",
    price: 450,
    quantity: 8,
    status: "active",
    createdAt: "2026-09-28",
  },
  {
    id: "my-listing-002",
    productId: "inv-005",
    productName: "Tea 500g",
    sku: "TEA-500G",
    category: "Beverages",
    price: 190,
    quantity: 10,
    status: "active",
    createdAt: "2026-09-26",
  },
];

export const demoResaleRequests = [
  {
    id: "RR-2001",
    listingId: "listing-001",
    productName: "Premium Tea 500g",
    quantity: 10,
    totalAmount: 1850,
    status: "pending",
    sellerName: "City Corner Store",
    createdAt: "2026-10-02",
  },
  {
    id: "RR-2002",
    listingId: "listing-002",
    productName: "Cooking Oil 5L",
    quantity: 5,
    totalAmount: 3100,
    status: "completed",
    sellerName: "Green Basket",
    createdAt: "2026-09-30",
  },
];

export const demoMerchantOrders = [
  {
    id: "ORD-3001",
    type: "procurement",
    productName: "Basmati Rice 25kg",
    quantity: 20,
    totalAmount: 37000,
    status: "accepted",
    createdAt: "2026-10-01",
  },
  {
    id: "ORD-3002",
    type: "procurement",
    productName: "Wheat Flour 25kg",
    quantity: 15,
    totalAmount: 16800,
    status: "preparing",
    createdAt: "2026-09-29",
  },
  {
    id: "ORD-3003",
    type: "resale",
    productName: "Premium Tea 500g",
    quantity: 10,
    totalAmount: 1850,
    status: "pending",
    createdAt: "2026-10-02",
  },
];

export const demoSupplierProducts = [
  {
    id: "sup-prod-001",
    name: "Basmati Rice 25kg",
    sku: "BAS-25KG",
    category: "Groceries",
    description: "Premium long-grain basmati rice.",
    price: 1850,
    stock: 240,
    status: "active",
  },
  {
    id: "sup-prod-002",
    name: "Wheat Flour 25kg",
    sku: "FLOUR-25KG",
    category: "Groceries",
    description: "Premium wheat flour for retail distribution.",
    price: 1120,
    stock: 320,
    status: "active",
  },
  {
    id: "sup-prod-003",
    name: "Toor Dal 25kg",
    sku: "DAL-25KG",
    category: "Groceries",
    description: "High-quality wholesale toor dal.",
    price: 3150,
    stock: 95,
    status: "active",
  },
];

export const demoSupplierOrders = [
  {
    id: "SUP-4001",
    merchantName: "Demo Merchant",
    productName: "Basmati Rice 25kg",
    quantity: 20,
    totalAmount: 37000,
    status: "pending",
    createdAt: "2026-10-01",
  },
  {
    id: "SUP-4002",
    merchantName: "City Corner Store",
    productName: "Wheat Flour 25kg",
    quantity: 15,
    totalAmount: 16800,
    status: "accepted",
    createdAt: "2026-09-30",
  },
  {
    id: "SUP-4003",
    merchantName: "Green Basket",
    productName: "Toor Dal 25kg",
    quantity: 10,
    totalAmount: 31500,
    status: "preparing",
    createdAt: "2026-09-28",
  },
];

export const demoAdminSuppliers = [
  {
    id: "supplier-001",
    name: "FreshMart Suppliers",
    email: "contact@freshmart.demo",
    products: 24,
    activeOrders: 8,
    status: "active",
  },
  {
    id: "supplier-002",
    name: "National Distributors",
    email: "sales@national.demo",
    products: 31,
    activeOrders: 12,
    status: "active",
  },
  {
    id: "supplier-003",
    name: "Wholesale Hub",
    email: "orders@wholesalehub.demo",
    products: 18,
    activeOrders: 4,
    status: "active",
  },
];

export const demoAdminOrders = [
  {
    id: "ORD-5001",
    merchantName: "Demo Merchant",
    supplierName: "FreshMart Suppliers",
    productName: "Basmati Rice 25kg",
    quantity: 20,
    totalAmount: 37000,
    status: "accepted",
    createdAt: "2026-10-01",
  },
  {
    id: "ORD-5002",
    merchantName: "City Corner Store",
    supplierName: "National Distributors",
    productName: "Sunflower Oil 15L",
    quantity: 10,
    totalAmount: 19800,
    status: "preparing",
    createdAt: "2026-09-30",
  },
  {
    id: "ORD-5003",
    merchantName: "Green Basket",
    supplierName: "Wholesale Hub",
    productName: "Toor Dal 25kg",
    quantity: 10,
    totalAmount: 31500,
    status: "completed",
    createdAt: "2026-09-28",
  },
];

export const demoLogistics = [
  {
    id: "SHIP-6001",
    orderId: "ORD-5001",
    merchantName: "Demo Merchant",
    supplierName: "FreshMart Suppliers",
    status: "in_transit",
    trackingNumber: "MN-TRK-10001",
    estimatedDelivery: "2026-10-05",
  },
  {
    id: "SHIP-6002",
    orderId: "ORD-5002",
    merchantName: "City Corner Store",
    supplierName: "National Distributors",
    status: "preparing",
    trackingNumber: "MN-TRK-10002",
    estimatedDelivery: "2026-10-06",
  },
  {
    id: "SHIP-6003",
    orderId: "ORD-5003",
    merchantName: "Green Basket",
    supplierName: "Wholesale Hub",
    status: "delivered",
    trackingNumber: "MN-TRK-10003",
    estimatedDelivery: "2026-10-02",
  },
];

export const demoAdminDashboard = {
  totalMerchants: 128,
  totalSuppliers: 24,
  activeOrders: 47,
  totalProcurementValue: 1847500,
};

export const demoSupplierOffers = {
  "Basmati Rice 25kg": [
    {
      id: "offer-001",
      supplierName: "FreshMart Suppliers",
      price: 1850,
      availableStock: 240,
      minimumOrderQuantity: 10,
      deliveryDays: 2,
      rating: 4.8,
    },
    {
      id: "offer-002",
      supplierName: "National Distributors",
      price: 1790,
      availableStock: 80,
      minimumOrderQuantity: 20,
      deliveryDays: 3,
      rating: 4.6,
    },
    {
      id: "offer-003",
      supplierName: "Wholesale Hub",
      price: 1920,
      availableStock: 300,
      minimumOrderQuantity: 5,
      deliveryDays: 1,
      rating: 4.7,
    },
  ],

  "Wheat Flour 25kg": [
    {
      id: "offer-004",
      supplierName: "FreshMart Suppliers",
      price: 1120,
      availableStock: 320,
      minimumOrderQuantity: 10,
      deliveryDays: 2,
      rating: 4.8,
    },
    {
      id: "offer-005",
      supplierName: "National Distributors",
      price: 1085,
      availableStock: 140,
      minimumOrderQuantity: 20,
      deliveryDays: 3,
      rating: 4.5,
    },
    {
      id: "offer-006",
      supplierName: "Wholesale Hub",
      price: 1150,
      availableStock: 500,
      minimumOrderQuantity: 5,
      deliveryDays: 1,
      rating: 4.7,
    },
  ],
};